const assert = require('assert');
const fs = require('fs');
const vm = require('vm');
const path = require('path');
const source = fs.readFileSync(path.join(__dirname, '../pebble/src/pkjs/pebble-js-app.js'), 'utf8');
const start = source.indexOf('function dedupeDepartures(');
const end = source.indexOf('function handlePositionUpdate(', start);
const sent = [];
const context = {encodeDeparture: () => '', IN_FAV_UPDATE: 1, sendToWatch: (type, payload) => sent.push(payload)};
vm.createContext(context);
vm.runInContext(source.slice(start, end), context);
const first = {run_ref: '123', route_type: 1, departure_time: '2026-09-30T09:53:00Z'};
const second = {...first, run_ref: '456'};
assert.equal(context.dedupeDepartures([first, second, first]).length, 2);
assert.equal(context.dedupeDepartures([first, {...first, departure_time: '2026-09-30T10:53:00Z'}]).length, 2);
assert.equal(context.dedupeDepartures([{}, {}]).length, 2);
const labels = ['Line works 8:30pm'];
context.handleFavUpdate({updates: [{button_id: 2, departures: [], message: 'No direct departures', disruption_labels: labels}]});
assert.equal(sent.pop(), '2||||No direct departures\x1eLine works 8:30pm');
assert.equal(labels.length, 1);
context.handleFavUpdate({updates: [{button_id: 2, departures: [first], message: 'No direct departures', disruption_labels: []}]});
assert.equal(sent.pop(), '2||||');
console.log('Departure identity and watch notice tests passed');
